version: '3.8'

services:
  backend:
    build:
      context: ./node-app
    volumes:
      - ./node-app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development

  frontend:
    build:
      context: ./react-app
    volumes:
      - ./react-app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:5173"
    environment:
      NODE_ENV: development