version: '3.8'

services:
  backend:
    build:
      context: ./node-app
    environment:
      NODE_ENV: production
    expose:
      - "4000"

  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend